# Generated by Django 5.0 on 2023-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='health',
            field=models.CharField(choices=[('good', 'Good Health'), ('needs_work', 'Needs Work'), ('poor', 'Poor Health')], default='good', max_length=20),
        ),
    ] 