# Generated by Django 5.0 on 2023-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_project_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this project is approved by admin'),
        ),
    ] 