# Generated by Django 5.2 on 2025-04-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_completed_early_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
