# Generated by Django 5.2 on 2025-04-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_item_delete_todolist'),
        ('main', '0009_teamjoinrequest'),
    ]

    operations = [
    ]
