# Generated by Django 5.2 on 2025-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_healthcheckcard_healthchecksession_healthcheckvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, help_text='Password for joining this team directly', max_length=100, null=True),
        ),
    ]
