# Generated by Django 5.2 on 2025-04-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_team_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('senior_manager', 'Senior Manager'), ('team_member', 'Team Member')], default='team_member', max_length=20)),
                ('technical_role', models.CharField(blank=True, choices=[('', 'Not Specified'), ('software_engineer', 'Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('mobile_developer', 'Mobile Developer'), ('web_developer', 'Web Developer'), ('data_scientist', 'Data Scientist'), ('data_engineer', 'Data Engineer'), ('data_analyst', 'Data Analyst'), ('devops_engineer', 'DevOps Engineer'), ('sre', 'Site Reliability Engineer'), ('qa_engineer', 'QA Engineer'), ('test_engineer', 'Test Engineer'), ('ui_designer', 'UI Designer'), ('ux_designer', 'UX Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('scrum_master', 'Scrum Master'), ('agile_coach', 'Agile Coach'), ('system_administrator', 'System Administrator'), ('network_engineer', 'Network Engineer'), ('security_engineer', 'Security Engineer'), ('database_administrator', 'Database Administrator'), ('cloud_architect', 'Cloud Architect'), ('solutions_architect', 'Solutions Architect'), ('technical_lead', 'Technical Lead'), ('engineering_manager', 'Engineering Manager'), ('cto', 'CTO'), ('other', 'Other')], default='', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this user is approved by admin')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_department_lead', models.BooleanField(default=False, help_text='Is this user a department lead?')),
                ('is_team_leader', models.BooleanField(default=False, help_text='Is this user a team leader?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='register.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='main.department')),
                ('teams', models.ManyToManyField(blank=True, related_name='team_members', to='main.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
