# Generated by Django 5.0 on 2023-12-10 13:00

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):
    dependencies = [
        ('register', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ] 