# Generated by Django 5.0 on 2023-12-10 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0003_company_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ] 