# Generated by Django 5.2 on 2025-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_company_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_code',
            field=models.CharField(default='d3d10759', max_length=20, unique=True),
        ),
    ]
