# Generated by Django 5.2 on 2025-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_company_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_code',
            field=models.CharField(default='72887402', max_length=20, unique=True),
        ),
    ]
