# Generated by Django 5.2 on 2025-04-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_company_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='access_code',
        ),
    ]
