# Generated by Django 5.2 on 2025-04-22 19:09

import register.models
from django.db import migrations, models
import random
import string

def generate_unique_codes(apps, schema_editor):
    Company = apps.get_model('register', 'Company')
    for company in Company.objects.all():
        # Generate a random code for existing companies
        chars = string.ascii_uppercase + string.digits
        company.access_code = ''.join(random.choice(chars) for _ in range(8))
        company.save()

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_company_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_code',
            field=models.CharField(default=register.models.generate_access_code, help_text='Code for employees to join company', max_length=10, unique=True),
        ),
        # Run the data migration after adding the field
        migrations.RunPython(generate_unique_codes, migrations.RunPython.noop),
    ]
