# Generated by Django 5.2 on 2025-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_company_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='technical_role',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('software_engineer', 'Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('mobile_developer', 'Mobile Developer'), ('web_developer', 'Web Developer'), ('data_scientist', 'Data Scientist'), ('data_engineer', 'Data Engineer'), ('data_analyst', 'Data Analyst'), ('devops_engineer', 'DevOps Engineer'), ('sre', 'Site Reliability Engineer'), ('qa_engineer', 'QA Engineer'), ('test_engineer', 'Test Engineer'), ('ui_designer', 'UI Designer'), ('ux_designer', 'UX Designer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('scrum_master', 'Scrum Master'), ('agile_coach', 'Agile Coach'), ('system_administrator', 'System Administrator'), ('network_engineer', 'Network Engineer'), ('security_engineer', 'Security Engineer'), ('database_administrator', 'Database Administrator'), ('cloud_architect', 'Cloud Architect'), ('solutions_architect', 'Solutions Architect'), ('technical_lead', 'Technical Lead'), ('engineering_manager', 'Engineering Manager'), ('cto', 'CTO'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
