# Generated by Django 5.2 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_completed_early_date_and_more'),
        ('register', '0009_userprofile_technical_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='main.team'),
        ),
    ]
