# Generated by Django 5.2 on 2025-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_remove_userprofile_team_userprofile_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_department_lead',
            field=models.BooleanField(default=False, help_text='Is this user a department lead?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_team_leader',
            field=models.BooleanField(default=False, help_text='Is this user a team leader?'),
        ),
    ]
