# Generated by Django 5.2 on 2025-04-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_simplify_company'),
        ('register', '0011_userprofile_is_department_lead_and_more'),
    ]

    operations = [
    ]
